name: 'Hello World'
description: 'build'
inputs:
  mavencycle:  # id of input
    description: 'maven life cycle'
    required: true
    default: 'package'
runs:
  using: "composite"
  steps:

  - name: Build with Maven
    run: mvn -B ${{ inputs.mavencycle }} --file pom.xml
    shell: bash
